### ISSUE TITLE
One Way Sync 

### ISSUE THREAD

**Issue by VishalKenn** [bailabs/tailpos#10]
products and categories when created in App are reflected on the Tailpos_Sync/Categories and in the "item list" but the products from the site are not getting synced into TailPos App
using following versions 
ERPNext: v11.1.21 (master)
Frappe Framework: v11.1.22 (master)
TailPOS Sync: v1.3.4 (master))

**Comment by iRaySpace** [comment]
Hello. Thanks for putting up. The TailPOS sync from ERPNext now requires you to tick 'In TailPOS' on Item.

**Comment by VishalKenn** [comment]
| 
17:49:48 web.1            | EXCEPTION
17:49:48 web.1            | Traceback (most recent call last):
17:49:48 web.1            |   File "/home/erpuser/master-bench/apps/tailpos_sync/tailpos_sync/sync_methods.py", line 174, in force_sync_from_erpnext_to_tailpos
17:49:48 web.1            |     query_data = frappe.db.sql(query, as_dict=True)
17:49:48 web.1            |   File "/home/erpuser/master-bench/apps/frappe/frappe/database.py", line 210, in sql
17:49:48 web.1            |     self._cursor.execute(query)
17:49:48 web.1            |   File "/home/erpuser/master-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
17:49:48 web.1            |     result = self._query(query)
17:49:48 web.1            |   File "/home/erpuser/master-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
17:49:48 web.1            |     conn.query(q)
17:49:48 web.1            |   File "/home/erpuser/master-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
17:49:48 web.1            |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
17:49:48 web.1            |   File "/home/erpuser/master-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
17:49:48 web.1            |     result.read()
17:49:48 web.1            |   File "/home/erpuser/master-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
17:49:48 web.1            |     first_packet = self.connection._read_packet()
17:49:48 web.1            |   File "/home/erpuser/master-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
17:49:48 web.1            |     packet.check_error()
17:49:48 web.1            |   File "/home/erpuser/master-bench/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
17:49:48 web.1            |     err.raise_mysql_exception(self._data)
17:49:48 web.1            |   File "/home/erpuser/master-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
17:49:48 web.1            |     raise errorclass(errno, errval)
17:49:48 web.1            | InternalError: (1054, u"Unknown column 'tabItem.barcode' in 'field list'")
17:49:48 web.1            | 
17:49:48 web.1            | 192.168.1.53 - - [30/Apr/2019 17:49:48] "POST /api/method/tailpos_sync.sync_pos.sync_data HTTP/1.1" 200 -
17:49:48 web.1            | INFO:werkzeug:192.168.1.53 - - [30/Apr/2019 17:49:48] "POST /api/method/tailpos_sync.sync_pos.sync_data HTTP/1.1" 200 -

i am gettting this exception trying to sync
i have assigned barcode to one product from the inventory and ticked as "in TailPOS"
please tell me if im doing something wrong

**Comment by iRaySpace** [comment]
You are not doing wrong. It seems that there is no custom field, barcode under Item. You can temporarily create one. Thanks for raising an issue. We will fix it.

**Comment by iRaySpace** [comment]
https://github.com/bailabs/tailpos-sync is updated with the `barcode` custom field. Thanks!
