### ISSUE TITLE
Description fetch issue

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#11]
After Last Update Description Sync not working properly 
![image](https://user-images.githubusercontent.com/12432802/57057306-5d7c9380-6cb0-11e9-82a0-0509a210e035.png)

**Comment by iRaySpace** [comment]
Hello @sammish 
Update your TailPOS and do a `bench update`

**Comment by sammish** [comment]
@iRaySpace okay now. But how can I get with Arabic language. I need both language in Printing
