### ISSUE TITLE
tailpos_sync.background_jobs.generate_si_from_receipts

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#14]
Item Synced, Receipt and Sales invoice created by System but getting this error

![image](https://user-images.githubusercontent.com/12432802/57072998-596c6800-6ce8-11e9-90a5-a16faa7e9688.png)

**Comment by iRaySpace** [comment]
Hello @sammish 
Can you update your TailPOS?

**Comment by sammish** [comment]
@iRaySpace yes now this working fine
