### ISSUE TITLE
Hiding Customer in Payment field

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#15]
Please Hide Customer in payment field, If you Select customer by mistake  from here it make duplicate customer in ERPNext.
![image](https://user-images.githubusercontent.com/12432802/57073301-56be4280-6ce9-11e9-8a7a-37dd7fb10925.png)

**Comment by iRaySpace** [comment]
Thanks for posting this one.

**Comment by iRaySpace** [comment]
Added 'Use Default Customer' field.
![Screenshot_2019-05-02-23-47-43](https://user-images.githubusercontent.com/5818544/57118980-6301d880-6d99-11e9-8261-e2386d7191e7.jpg)

**Comment by sammish** [comment]
@iRaySpace TailPOS updated but not showing above setting (User Default Customer)

**Comment by iRaySpace** [comment]
Let me try to check on this one.

**Comment by iRaySpace** [comment]
Try to update TailPOS again.

**Comment by sammish** [comment]
@iRaySpace yes,working now
