### ISSUE TITLE
Table Change

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#20]
Table change Not working , whenever click in table change TailPOS become Hang and no action happening 

![image](https://user-images.githubusercontent.com/12432802/57174421-4de38300-6e47-11e9-916e-cd7ccb79901d.png)

**Comment by iRaySpace** [comment]
Hello @sammish. Have you tried updating your bench?

**Comment by sammish** [comment]
NoSent from my Huawei Mobile-------- Original Message --------Subject: Re: [bailabs/tailpos] Table Change (#20)From: Ivan Ray Altomera To: bailabs/tailpos CC: sammish ,Mention Hello @sammish. Have you tried updating your bench?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bailabs/tailpos/issues/20#issuecomment-489481810",
"url": "https://github.com/bailabs/tailpos/issues/20#issuecomment-489481810",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
