### ISSUE TITLE
Take away not Showing 

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#23]
Take away not showing TailPOS 

![image](https://user-images.githubusercontent.com/12432802/57174464-1cb78280-6e48-11e9-9d12-6cdee8162574.png)

**Comment by iRaySpace** [comment]
Hello @sammish I have fixed this one. Update the TailPOS. Thanks!

**Comment by sammish** [comment]
No Item Selected But Take away Showing 

![image](https://user-images.githubusercontent.com/12432802/57271835-cb063680-7099-11e9-88a4-910e54061da9.png)

**Comment by sammish** [comment]
If you select and make take way it will be showing like this

![image](https://user-images.githubusercontent.com/12432802/57271933-043ea680-709a-11e9-9691-d6005ecbe8fc.png)

**Comment by sammish** [comment]
Whenever opening View Order there is also showing Take away 

![image](https://user-images.githubusercontent.com/12432802/57272016-63042000-709a-11e9-8249-c39007449e10.png)

**Comment by iRaySpace** [comment]
Hello @sammish. The take away option will not be available when you are viewing orders.

**Comment by iRaySpace** [comment]
The new update will also disable if there are no items on the receipt.

**Comment by sammish** [comment]
@iRaySpace okay
