### ISSUE TITLE
URL Not Working With http & Queueing Server Not Showing

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#30]
URL Not Working With http  
![image](https://user-images.githubusercontent.com/12432802/57522974-55fe5f80-732c-11e9-9bbc-2722907fb381.png)

**Comment by sammish** [comment]
Queueing Server Not Showing
![image](https://user-images.githubusercontent.com/12432802/57523065-a4136300-732c-11e9-9040-f873011e3a17.png)

**Comment by iRaySpace** [comment]
Hello. Input the Device ID as lowercase.

**Comment by iRaySpace** [comment]
When was this last updated?

**Comment by sammish** [comment]
@iRaySpace yesteday

**Comment by iRaySpace** [comment]
What device is this?

**Comment by sammish** [comment]
@iRaySpace Samsung

**Comment by iRaySpace** [comment]
Hello @sammish Can you try to reinstall your TailPOS and re-sync again?

**Comment by sammish** [comment]
@iRaySpace its not working
