### ISSUE TITLE
Fix :Remarks not working from TailPOS

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#41]
Remarks not working from TailPOS . its showing QTY and Price in TailPOS and we cannot add whenever making takaway order from TailPOS

**Comment by iRaySpace** [comment]
Hello @sammish 

I have updated the application. The idea for remarks in TailPOS is to add "*" at the end of the items in ERPNext.
![image](https://user-images.githubusercontent.com/5818544/58399893-32594a00-808c-11e9-93c2-8c2001867c2f.png)

**Comment by sammish** [comment]
@iRaySpace okay
