### ISSUE TITLE
Fix : Printing Not working from TailPOS & TailOrder 

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#42]
Printing not working from TailPOS & TailOrder 

![image](https://user-images.githubusercontent.com/12432802/58231251-35c49c80-7d3f-11e9-887c-4c441da1535a.png)

![image](https://user-images.githubusercontent.com/12432802/58231259-3cebaa80-7d3f-11e9-9898-e4b15bb34f8f.png)

**Comment by ccfiel** [comment]
for now we support usb printer not network printer

**Comment by sammish** [comment]
@ccfiel okay but USB printer also not working which is  i have exist. any way  I ordered new printer which is your are successfully tested
