### ISSUE TITLE
Fix : Add Item stacking after Remarks 

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#44]
Please add Item Stack after remarks in TailPOS

![image](https://user-images.githubusercontent.com/12432802/58760691-2960f080-8544-11e9-8cb9-2d7229938cdb.png)

**Comment by sammish** [comment]
@ccfiel @iRaySpace Please fix I wanna go live within two days

**Comment by iRaySpace** [comment]
Added Item Stacking settings on new update.
