### ISSUE TITLE
Fix : Remarks Full Item not Showing in TailPOS

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#45]
Remarks Full Item not Showing in TailPOS but Showing in TailOrder

![remarks](https://user-images.githubusercontent.com/12432802/58760844-fcadd880-8545-11e9-945b-33e7980993a7.gif)

**Comment by sammish** [comment]
@ccfiel @iRaySpace Please fix I wanna go live within two days

**Comment by iRaySpace** [comment]
This is due to duplicating the Item; therefore, id generation is skipped.
