### ISSUE TITLE
Fix : Item void (-ve )Not working from TailPOS

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#48]
Item void (-ve )Not working from TailPOS  Takeaway & Direct Billing 

![Item](https://user-images.githubusercontent.com/12432802/59422017-5335d500-8dd8-11e9-90ed-a23d0b630131.gif)
![Item1](https://user-images.githubusercontent.com/12432802/59422027-5761f280-8dd8-11e9-9b45-05898f045ef7.gif)

**Comment by iRaySpace** [comment]
This is fixed on new update TailOrder server because of table auto generation

**Comment by sammish** [comment]
@iRaySpace okay noted, thanks
