### ISSUE TITLE
Translation to other languages 

### ISSUE THREAD

**Issue by Helkyd** [bailabs/tailpos#50]
The system is only available in English.. What if I need Portuguese?

**Comment by ccfiel** [comment]
We are working translation module with in this month. You can help us translate it in Portuguese.

**Comment by Helkyd** [comment]
Of course.
Just send me the files with English and will translate.

Rgrds
Hélio de Jesus

**Comment by wellart** [comment]
i can help with indonesian

**Comment by ccfiel** [comment]
@wellart @Helkyd translation is ready just create a new file under https://github.com/bailabs/tailpos/tree/master/src/translations and copy https://github.com/bailabs/tailpos/blob/master/src/translations/en.js  to anonther file ang change it.

**Comment by wellart** [comment]
done

**Comment by ccfiel** [comment]
https://github.com/bailabs/tailpos/pull/56
https://github.com/bailabs/tailpos/pull/55
