### ISSUE TITLE
Please support MPT II

### ISSUE THREAD

**Issue by wellart** [bailabs/tailpos#52]
can you add this printer to work on tailpos?
http://www.hprt.com/Product/Mobile-Printers/MPT2.html

**Comment by ccfiel** [comment]
@wellart I think this will work because its ESC/POS compatible. Try and give us feedback.

**Comment by wellart** [comment]
i already try, the printer not show in the printer list

**Comment by ccfiel** [comment]
I see. If we do not have the printer in our end its difficult to test
