### ISSUE TITLE
When select the item no name or description shown 

### ISSUE THREAD

**Issue by Helkyd** [bailabs/tailpos#53]
After selecting the item no description or item code shown... How will the user know which items inserted? 
![Screenshot_20190702-175926](https://user-images.githubusercontent.com/20396898/60532286-e2a61800-9cf4-11e9-9087-bb547db247b1.png)

**Comment by ccfiel** [comment]
We have tested in a 10 inches tablet.

**Comment by Helkyd** [comment]
I have just done on a wintec pos and

**Comment by Helkyd** [comment]
Here the screenshot from the Wintec POS 14"

**Comment by ccfiel** [comment]
We tested in our 10" tablet it work ok. See screenshot

![Screenshot_2019-07-03-03-44-43](https://user-images.githubusercontent.com/1788360/60573153-aed8fa00-9da9-11e9-8803-9aacf7a022b8.jpg)

**Comment by Helkyd** [comment]
I have checked the item to see if there is any extra settings on Tail to
show the item name but could not find it.
Something is not allowing it to show the item name... and even for smaller
screen you should be able to play with the Font Size so user can know what
items he has inserted...

**Comment by Helkyd** [comment]
Just made a test by creating a new Item on TAILPOS and it shows the item
name but for the items Synced from ERPNext not showing the name ....
Just check the Code.

**Comment by ccfiel** [comment]
You can edit the source to change the font and compile it so that fit in the screen to your tablet or we can make it configurable you can sponsor for that feature or can submit PR to us.

**Comment by Helkyd** [comment]
Hi Chris,

Not yet playing with the source code .... :)
Just to add items created on TAILPOS and Synced with ERPNext are still
visible on TAILPOS even with "in TailPOS" not selected.. To remind that the
item was created on TAILPOS so i think it should be ticked by default.

**Comment by ccfiel** [comment]
Ok noted in ticked by default.
