### ISSUE TITLE
When Syncing should select the default Company

### ISSUE THREAD

**Issue by Helkyd** [bailabs/tailpos#54]
When you Sync with ERPNext it should check if default company exists and select.
It should also allow the user to select which company he wants to use on the System...

For example on mine i have 5 companies and when TailPos Syncs i don't know which company as i have to write on the company either wrong or non-existing company.

**Comment by ccfiel** [comment]
you have to configure your POS profile

**Comment by Helkyd** [comment]
How does the tailpos user links to erpnext user to see the profile?
Because I have profiles created but the users on Tailpos are not created on ERPNext.
