### ISSUE TITLE
Translation not to all items yet

### ISSUE THREAD

**Issue by Helkyd** [bailabs/tailpos#60]
After selecting the language and restart the App some translations not yet not... 
Was the file (en) completed when translation in PT done?
Also advise on languages keep PT-PT and PT-BR and remove PT (single).
![Screenshot_20190710-125627](https://user-images.githubusercontent.com/20396898/60967466-a1c08b80-a312-11e9-9c01-b75da592e504.png)

**Comment by jiloysss** [comment]
Hello @Helkyd thanks for reporting. Kindly update TailPOS app, we pushed a fix for the translation in Payment Interface. For other words that were not translated, we need help in translating them. If you want to help (I mean, please do), this is the file for pt-BR / pt-PT

https://github.com/bailabs/tailpos/blob/master/src/translations/pt.js

the words that need translation are at the bottom of the file.

Regards,
Jan
