### ISSUE TITLE
App closing when Sync button is hit

### ISSUE THREAD

**Issue by prasannatp** [bailabs/tailpos#7]
I installed the app in Amazon Fire 10 inch tablet wherein everything is shown but as the sync button hit the app is closing automatically.

**Comment by iRaySpace** [comment]
Hello @prasannatp,
Can you check the new update if this issue is still existing?

**Comment by ccfiel** [comment]
have you tested it again @prasannatp ?

**Comment by prasannatp** [comment]
Hi @ccfiel & @iRaySpace ,

I reinstalled in the TailPOS in ERPNext and also in the tablet but the App is closing when Sync button is hit.

**Comment by ccfiel** [comment]
Hello @prasannatp 

can you send the credentials (Username and password) and URL that you used in tailpos in my email ccfiel @ bai.ph for us to debug it in our end. Thanks
